apiVersion: apps/v1
kind: Deployment
metadata: 
  name: whatnxt-ui-deployment
  namespace: whatnxt
  labels: 
    app: whatnxt 
    tier: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatnxt
      tier: front-end
  template:
    metadata: 
      name: whatnxt-app-pod
      labels:
        app: whatnxt
        tier: front-end
    spec:
      containers:
        - name: whatnxt-ui
          image: dkagitha/whatnxt-ui:1.4.10-SNAPSHOT
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: whatnxt-ui-service
  namespace: whatnxt
  labels:
    app: whatnxt
    tier: front-end
spec: 
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
      app: whatnxt 
      tier: front-end
      


