apiVersion: v1
kind: Namespace
metadata:
  name: whatnxt
  labels:
    app: whatnxt

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: whatnxt-app-deployment
  namespace: whatnxt
  labels: 
    app: whatnxt 
    tier: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whatnxt
      tier: back-end
  template:
    metadata: 
      name: whatnxt-app-pod
      labels:
        app: whatnxt
        tier: back-end
    spec:
      containers:
        - name: whatnxt-app
          image: dkagitha/whatnxt-app:1.4.10-SNAPSHOT
          ports:
          - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: whatnxt-app-service
  labels:
    app: whatnxt
    tier: back-end
spec: 
  ports:
  - port: 5000
    targetPort: 5000
  selector:
      app: whatnxt 
      tier: back-end


