apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatnxt-ui-Deployment
  namespace: whatnxt
  labels:
    app: whatnxt-ui
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: whatnxt-ui
  template:
    metadata:
      labels:
        app: whatnxt-ui
    spec:
      containers:
      - name: whatnxt-ui
        image: dkagitha/whatnxt-ui:1.5.1-SNAPSHOT
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: whatnxt-ui
  namespace: whatnxt
spec:
  selector:
    app: wnhatnx-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
          
        





